[package]
name = "mysql-audit-extend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
daemonize = "0.4.1"
delay_timer = "0.11.3"
users = "0.11.0"
